version: '3.8'
services:
  benutzerverwaltung:
    build:
      context: ./benutzerverwaltung # Pfad zum Ordner mit dem Dockerfile
    image: ${DOCKER_USER}/benutzerverwaltung:latest

  lagerverwaltung-core:
    build:
      context: ./lagerverwaltung-core
    image: ${DOCKER_USER}/lagerverwaltung-core:latest

  lagerverwaltung-web:
    build:
      context: ./lagerverwaltung-web
    image: ${DOCKER_USER}/lagerverwaltung-web:latest
