name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Hier übergeben wir die GitHub-Variable an Docker Compose, 
      # damit die Images den richtigen Namen bekommen.
      - name: Build Images via Docker Compose
        env:
          DOCKER_USER: ${{ vars.DOCKER_USER }}
        run: docker compose build

      - name: Push Images to Docker Hub
        env:
          DOCKER_USER: ${{ vars.DOCKER_USER }}
        run: docker compose push
